extends Node

class_name GlobalEnums

enum NPCState { NUEVO, APROBADO, EN_VALIDACION, DESAPROBADO }
enum Incidencia { 
	NINGUNA, 
	NOMBRE_CEDULA_DIFERENTE, NOMBRE_CARNET_DIFERENTE, NOMBRE_PASE_DIFERENTE,
	FECHA_CEDULA_CADUCADA, CEDULA_OLVIDADA,
	FOTO_CARNET_DIFERENTE, CARNET_OLVIDADO, CARRERA_DIFERENTE,
	PASE_VISITANTE_OLVIDADO,
	SOSPECHOSO 
}
