extends Node

class_name GlobalEnums

enum NPCState { NUEVO, APROBADO, EN_VALIDACION, DESAPROBADO }
enum Incidencia { 
	NINGUNA, 
	NOMBRE_CEDULA_DIFERENTE, NOMBRE_CARNET_DIFERENTE, 
	FECHA_CEDULA_CADUCADA, 
	FOTO_CARNET_DIFERENTE, 
	SOSPECHOSO 
}
